3viknavinir/Models/AlphabetizedTextsViewmodel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace _3viknavinir.Models
{
	public class AlphabetizedTextsViewmodel : _3viknaContext
    {
        public IEnumerable<Media> allMedia {get; set;}
    }
}

3viknavinir/Models/ViewModels/AlphabetizedTextsViewModel.cs
using _3viknavinir.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace _3viknavinir.Models
{
	public class AlphabetizedTextsViewmodel
    {
        public List<MediaUpvoteViewModel> allMedia {get; set;}
		public int pageCount { get; set; }
    }
}

3viknavinir/Controllers/ListTranslationsController.cs
using _3viknavinir.Models;
using _3viknavinir.Models.ViewModels;
using _3viknavinir.Repo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace _3viknavinir.Controllers
{
	[HandleError]
    public class ListTranslationsController : Controller
    {
		const int ITEMSPERPAGE = 10;

        // GET: /ListTranslations/
        public ActionResult Index()
        {
            return View();
        }

		public ActionResult AlphabetizedTexts(int? id)
		{
			using (UserRepo userRepo = new UserRepo())
			{
				using (TranslationRepo translationRepo = new TranslationRepo())
				{
					using(MediaRepo mediarepo = new MediaRepo())
					{
						int realid = 0;

						if(id.HasValue)
						{
							realid = id.Value;
						}
						
                        var viewModel = new AlphabetizedTextsViewmodel();

						var count = (from m in mediarepo.GetAllMedia()
											   select m).Count();
						
                        viewModel.pageCount = (count / ITEMSPERPAGE) + 1;

						var allmedia = (from m in mediarepo.GetAllMedia()
										orderby m.title ascending
										select m).Skip(realid * ITEMSPERPAGE).Take(ITEMSPERPAGE);

						viewModel.allMedia = new List<MediaUpvoteViewModel>();
						
                        foreach(var item in allmedia)
						{
							MediaUpvoteViewModel mediaUpvote = new MediaUpvoteViewModel();
							
                            mediaUpvote.media = item;
							
                            var translation = translationRepo.GetTranslationByMediaID(item.ID);
							
                            if(translation != null)
							{
								mediaUpvote.upvotes = translationRepo.GetTranslationByMediaID(item.ID).Upvote.Count;
							}
							
                            viewModel.allMedia.Add(mediaUpvote);
						}

						if(allmedia != null)
						{
							return View(viewModel);
						}
					}
					return View();
				}
			}
		}


		public JsonResult UpvoteMedia(int mediaId)
		{
			using (TranslationRepo translationRepo = new TranslationRepo())
			{
				using(UpvoteRepo upvoteRepo = new UpvoteRepo())
				{
					var translationId = translationRepo.GetTranslationByMediaID(mediaId).ID;
					var userId = User.Identity.GetUserId();
					var upvotes = upvoteRepo.GetUpvotesByTranslationID(translationId);
					
                    var userUpvote = (from u in upvotes
									 where u.userID == userId 
									 select u).FirstOrDefault();
									 
					if(userUpvote != null)				// User has already upvoted this item
					{
						return Json(new { upvotes = (translationRepo.GetTranslationByMediaID(mediaId).Upvote.Count - 1) });
					} 
                    else
					{
						Upvote newUpvote = new Upvote();
						newUpvote.userID = userId;
						newUpvote.translationID = translationId;
						newUpvote.requestID = null;
						newUpvote.discussionID = null;

						upvoteRepo.AddUpvote(newUpvote);
						return Json(new { upvotes = translationRepo.GetTranslationByMediaID(mediaId).Upvote.Count });
					}
				}
			}
		}
	}
}

3viknavinir/Controllers/SearchController.cs
using _3viknavinir.Repo;
using _3viknavinir.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _3viknavinir.Controllers
{
    public class SearchController : Controller
    {
        // GET: /Search/
		public ActionResult SearchMediaView(string searchString)
		{
			using (MediaRepo mediaRepo = new MediaRepo())
			{
				using (CategoryRepo categoryRepo = new CategoryRepo())
				{
					using (TranslationRepo translationRepo = new TranslationRepo())
					{
						if(!String.IsNullOrEmpty(searchString))
						{
							var movies = (from m in mediaRepo.GetMediaLike(searchString)
										  select m);

							var viewModel = new SearchMediaViewModel();
							
                            viewModel.searchedMedia = movies;

							if (movies != null)
							{
								return View(viewModel);
							}
						}
					}
				}
			}
			return View( );
		}
		
		public ActionResult SearchRequestView(string searchString)
		{
			using (RequestRepo requestRepo = new RequestRepo())
			{
				if (!String.IsNullOrEmpty(searchString))
				{
					var requests = (from m in requestRepo.GetRequestLike(searchString)
								    select m);

					var viewModel = new SearchRequestViewModel();
					
                    viewModel.searchedRequests = requests;

					if (requests != null)
					{
						return View(viewModel);
					}
				}
				else
				{
					return View();
				}
			}
			return View();
		}
	}
}

3viknavinir/Views/ListTranslations/AlphabetizedTexts.cshtml
@model _3viknavinir.Models.AlphabetizedTextsViewmodel
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Textar A-Ö";
}
    <div class="breadcrumb">
        <ul class="crumbs">
            <li class="crumb crumb-first">
                @Html.ActionLink("SÍÁT", "Index", "Home")
            </li>
            <li class="crumb crumb-last">
                <span class="crumb-seperator"> > </span>
                @Html.ActionLink("Textar A-Ö", "AlphabetizedTexts", "ListTranslations")
            </li>
        </ul>
    </div>
    <h2>Textar A-Ö</h2>
    @*Erla*@
    <div id="searchBox">
        @using (Html.BeginForm("SearchMediaView", "Search", FormMethod.Get))
        {
            @Html.TextBox("SearchString")
            <input type="submit" value="Leita" class="btn btn-default" id="searchButton" />
        }
    </div>
<form action="/Translation/Translate" class="row">
	<input type="submit" value="" id="addRequestButton" />
	<span id="requestLink">@Html.ActionLink("Bæta við þýðingu", "Translate", "Translation", new { @class = "addRequestLine" })</span>
</form>
    <div class="alphabetizedTextDiv">
        <table id="AlphabetListTable" class="table-striped">
            <thead>
                <tr class="requestRow">
                    <th>Nafn</th>
                    <th>Ártal</th>
                    <th>Upvote</th>
                    <th>Niðurhal</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.allMedia)
                {
                    <tr class="requestRow">
                        <td class="alphabetname">@Html.ActionLink(item.media.title, "Details", "Translation", new { id = item.media.ID }, null)</td>
                        <td class="alphabetYear">@item.media.yearOfRelease</td>
                        <td class="alphabetUpvote">@item.upvotes
                            @if (Request.IsAuthenticated)
                            {
                                <a href="#" class="upvoteTranslation glyphicon glyphicon-thumbs-up glyphicon-position" id="@item.media.ID"></a>
                            }
                        </td>
                        <td><a href="~/Translation/Download/@item.media.ID" class="glyphicon glyphicon-download glyphicon-position"></a></td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="pageCount">
            @for (int i = 0; i < Model.pageCount ; i++)
            {
                @Html.ActionLink((i + 1).ToString(), "AlphabetizedTexts", "ListTranslations", new { id = i }, null)
            }
        </div>
    </div>