3viknavinir/Controllers/CategoryController.cs
using _3viknavinir.Repo;
using _3viknavinir.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _3viknavinir.Controllers
{
    [HandleError]
    public class CategoryController : Controller
    {
        // GET: /Category/
        public ActionResult Index()
        {
            return View();
        }

		public ActionResult Categories()
		{
			return View();
		}
        public ActionResult Documentary()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var documentaries = ( from m in mediaRepo.GetMediaByCategoryID( 15 )
                                   orderby m.title descending
                                   select m );
                
                if ( documentaries != null )
                {
                    return View( documentaries );
                }
            }
            return View( );
        }
        public ActionResult Action()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var actions = ( from m in mediaRepo.GetMediaByCategoryID( 9 )
                                   orderby m.title descending
                                   select m );
                
                if ( actions != null )
                {
                    return View( actions );
                }
            }
            return View( );
        }
        public ActionResult Adventure()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var adventures = ( from m in mediaRepo.GetMediaByCategoryID( 1 )
                                 orderby m.title descending
                                 select m );
                
                if ( adventures != null )
                {
                    return View( adventures );
                }
            }
            return View( );
        }
        public ActionResult Anime()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var anime = ( from m in mediaRepo.GetMediaByCategoryID( 14 )
                                 orderby m.title descending
                                 select m );
                
                if ( anime != null )
                {
                    return View( anime );
                }
            }
            return View( );
        }
        public ActionResult Comedy()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var comedies = ( from m in mediaRepo.GetMediaByCategoryID( 2 )
                                 orderby m.title descending
                                 select m);
                
                if ( comedies != null)
                {
                    return View( comedies );
                }
            }
            return View();
        }
        public ActionResult Drama()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var drama = ( from m in mediaRepo.GetMediaByCategoryID( 11 )
                                 orderby m.title descending
                                 select m );
                
                if ( drama != null )
                {
                    return View( drama );
                }
            }
            return View( );
        }
        public ActionResult Family()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var family = ( from m in mediaRepo.GetMediaByCategoryID( 3 )
                                 orderby m.title descending
                                 select m );
                
                if ( family != null )
                {
                    return View( family );
                }
            }
            return View( );
        }
        public ActionResult Horror()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var horror = ( from m in mediaRepo.GetMediaByCategoryID( 8 )
                                 orderby m.title descending
                                 select m );
                
                if ( horror != null )
                {
                    return View( horror );
                }
            }
            return View( );
        }
        public ActionResult Icelandic()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var icelandics = ( from m in mediaRepo.GetMediaByCategoryID( 4 )
                                 orderby m.title descending
                                 select m );
                
                if ( icelandics != null )
                {
                    return View( icelandics );
                }
            }
            return View( );
        }
        public ActionResult Kids()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var kids = ( from m in mediaRepo.GetMediaByCategoryID( 10 )
                                 orderby m.title descending
                                 select m );
                
                if ( kids != null )
                {
                    return View( kids );
                }
            }
            return View( );
        }
        public ActionResult Musical()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var musicals = ( from m in mediaRepo.GetMediaByCategoryID( 5 )
                                 orderby m.title descending
                                 select m );
                
                if ( musicals != null )
                {
                    return View( musicals );
                }
            }
            return View( );
        }
        public ActionResult Romantic()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var romantics = ( from m in mediaRepo.GetMediaByCategoryID( 6 )
                                 orderby m.title descending
                                 select m );
                
                if ( romantics != null )
                {
                    return View( romantics );
                }
            }
            return View( );
        }
        public ActionResult Scifi()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var scifis = ( from m in mediaRepo.GetMediaByCategoryID( 12 )
                                 orderby m.title descending
                                 select m );
               
                if ( scifis != null )
                {
                    return View( scifis );
                }
            }
            return View( );
        }
        public ActionResult Show()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var shows = ( from m in mediaRepo.GetMediaByCategoryID( 13 )
                                 orderby m.title descending
                                 select m );
                
                if ( shows != null )
                {
                    return View( shows );
                }
            }
            return View( );
        }
        public ActionResult Thriller()
        {
            using ( MediaRepo mediaRepo = new MediaRepo( ) )
            {
                var thrillers = ( from m in mediaRepo.GetMediaByCategoryID( 7 )
                                 orderby m.title descending
                                 select m );
               
                if ( thrillers != null )
                {
                    return View( thrillers );
                }
            }
            return View( );
        }
        public ActionResult Other()
        {
            using (MediaRepo mediaRepo = new MediaRepo())
            {
                var others = (from m in mediaRepo.GetMediaByCategoryID(16)
                                orderby m.title descending
                                select m);
               
                if (others != null)
                {
                    return View(others);
                }
            }
            return View();
        }
	}
}

3viknavinir/Controllers/HomeController.cs
using _3viknavinir.Repo;
using _3viknavinir.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _3viknavinir.Controllers
{
	[HandleError]
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			using(MediaRepo mediaRepo = new MediaRepo())
			{
                using (TranslationRepo translationRepo = new TranslationRepo())
                {
                    using (RequestRepo RequestRepo = new RequestRepo())
                    {
                        var newestMedia = (from t in translationRepo.GetAllTranslations()
                                           join m in mediaRepo.GetAllMedia() on t.mediaID equals m.ID
                                           orderby t.dateAdded descending
                                           select m).Take(10);

                        var viewModel = new IndexViewModel();

                        viewModel.recentMedia = newestMedia;

                        var recentRequest = (from r in RequestRepo.GetAllRequests()
                                           orderby r.dateOfRequest descending
                                           select r).Take(10);

                        viewModel.recentRequests = recentRequest;

                        if (newestMedia != null && recentRequest != null)
                        {
                            return View(viewModel);
                        }
                    }
                }
			}
        
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}

        public ActionResult ProcessRequest()
        {
            return View();
        }

		public ActionResult FAQ()
		{
			ViewBag.Message = "Algengar spurningar.";

			return View();
		}

        public ActionResult ForgotPassword()
        {
            ViewBag.Message = "Gleymt Lykilorð";

            return View();
        }

        public ActionResult Error404()
        {
            return View();
        }
	}
}

3viknavinir/Controllers/SearchController.cs
using _3viknavinir.Repo;
using _3viknavinir.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _3viknavinir.Controllers
{
    public class SearchController : Controller
    {
        // GET: /Search/
		public ActionResult SearchMediaView(string searchString)
		{
			using (MediaRepo mediaRepo = new MediaRepo())
			{
				using (CategoryRepo categoryRepo = new CategoryRepo())
				{
					using (TranslationRepo translationRepo = new TranslationRepo())
					{
						if(!String.IsNullOrEmpty(searchString))
						{
							var movies = (from m in mediaRepo.GetMediaLike(searchString)
										  select m);

							var viewModel = new SearchMediaViewModel();
							
                            viewModel.searchedMedia = movies;

							if (movies != null)
							{
								return View(viewModel);
							}
						}
					}
				}
			}
			return View( );
		}
		
		public ActionResult SearchRequestView(string searchString)
		{
			using (RequestRepo requestRepo = new RequestRepo())
			{
				if (!String.IsNullOrEmpty(searchString))
				{
					var requests = (from m in requestRepo.GetRequestLike(searchString)
								    select m);

					var viewModel = new SearchRequestViewModel();
					
                    viewModel.searchedRequests = requests;

					if (requests != null)
					{
						return View(viewModel);
					}
				}
				else
				{
					return View();
				}
			}
			return View();
		}
	}
}

3viknavinir/Views/Home/About.cshtml
<div class="about">
    @{
        ViewBag.Title = "About";
    }

    <div class="breadcrumb">
        <ul class="crumbs">
            <li class="crumb crumb-first">
                @Html.ActionLink("SÍÁT", "Index", "Home")
            </li>
            <li class="crumb crumb-last">
                <span class="crumb-seperator"> > </span>
                @Html.ActionLink("Um okkur", "About", "Home")
            </li>
        </ul>
    </div>
    <div class="aboutText">
        <h2>Samfélag Íslenskra Áhugamanna um Texta</h2>
        <p class="aboutAbout">


            Samfélag Íslenskra Áhugamanna um Texta (SÍÁT) er nafn vinnuhóps í verklegu námskeiði
            tölvunarfræði á 2. önn í Háskóla Reykjavíkur. Hópurinn fékk það verk að búa til vefsíðu sem að
            gerði notanda kleift að hlaða inn .srt skrá og þýða hana yfir á önnur tungumál. Hver
            sem er getur sótt texta til að setja inná myndefni.
            Vinnuhóp SÍÁT skipa Erla Harðardóttir, Fanney Hrund Jónasdóttir, Grímur Kristinsson,
            Liljar Már Þorbjörnsson, Steinunn Marta Friðriksdóttir og Svava Dögg Björgvinsdóttir.
        </p>
    </div>
    <div class="aboutPhoto">
        <img src="@Url.Content("~/Content/workaboutpicjpg.jpg")" alt="Vinnuhopur SíáT" class="aboutPhoto" />
        <p class="aboutPhoto">Falleg mynd af okkur</p>
    </div>
</div>

3viknavinir/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Hafa samband";
}
<div class="breadcrumb">
    <ul class="crumbs">
        <li class="crumb crumb-first">
            @Html.ActionLink("SÍÁR", "Index", "Home")
        </li>
        <li class="crumb crumb-last">
            <span class="crumb-seperator"> > </span>
            @Html.ActionLink("Hafa samband", "Contact", "Home")
        </li>
    </ul>
</div>
<h2>@ViewBag.Title</h2>
<p class="contactText">
    Síðan SÍÁT er verkefni nemanda við Háskólann í Reykjavík. Höfuðstöðvar síðunnar eru innan veggja
    skólans og því aðeins hægt að hafa samband við umsjónarmenn vefsíðunnar í gegnum
    fyrirspurnarform hér að neðan.
</p>

<form class="form-control-static" method="post" action="ProcessRequest">
    <div>
        <div>
        <label>Nafn</label>
            <input type="text" name="userName" class="form-control" />
        <label>Tölvupóstfang</label>
            <input type="text" name="userEmail" class="form-control" />
        <label>Fyrirspurn</label>
            <textarea class="form-control" name="userRequest" cols="45" rows="4"></textarea>
    </div>
    </div>
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Senda" />
    </div>
</form>

3viknavinir/Views/Home/FAQ.cshtml
@{
    ViewBag.Title = "Algengar spurningar";
}
<div class="breadcrumb">
    <ul class="crumbs">
        <li class="crumb crumb-first">
            @Html.ActionLink("SÍÁT", "Index", "Home")
        </li>
        <li class="crumb crumb-last">
            <span class="crumb-seperator"> > </span>
            @Html.ActionLink("FAQ", "FAQ", "Home")
        </li>
    </ul>
</div>

<h2>@ViewBag.Title</h2>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>



<div id="accordion">
    <h3>Hvernig sæki ég texta?</h3>
    <div>
        <p>
            Það er hægt á mörgum stöðum, allstaðar þar sem þú sérð lista af myndum,
            til dæmis ef þú ferð á forsíðu eða leitar að mynd er dálkur til vinstri með lítilli ör sem byrjar niðurhal.
            Einnig ef þú velur ákveðna mynd er hnappur sem segir "Hlaða niður þýðingu" og þegar ýtt er á hann byrjar niðurhal.
            Góða skemmtun!
        </p>
    </div>
    <h3>Hvernig breyti ég lykilorðinu mínu?</h3>
    <div>
        <p>
            Til þess að breyta lykilorðinu þínu þarftu að fara á @Html.ActionLink("þínar síður", "Manage", "Account") sem er í hægra efra horni þar sem notendanafnið þitt stendur, eða ýta @Html.ActionLink("\"Hér\"", "Manage", "Account").
            Þar inni getur þú breytt lykilorðinu þínu.
        </p>
    </div>
    <h3>Hvernig set ég inn skrá til þess að þýða?</h3>
    <div>
            <p>
            Undir flipanum @Html.ActionLink("\"Þýða\"","Translate", "Translation") er form til þess að bæta við þýðingu á nýrri mynd.
            Þar er hægt að hlaða inn .srt skrá, jafnvel á erlendu tungumáli til þess að hafa til hliðsjónar við þýðingu.
            Einnig er hægt að hlaða inn .srt skrá á öðru tungumáli sé ekki önnur slík til staðar inni á síðunni þar sem texta fyrir ákveðna mynd er breytt.
        </p>
    </div>
    <h3>Hvernig þýði ég texta?</h3>
    <div>
        <p>
            Þegar þú ert kominn inn í "Breyta þýðingu" sérðu nokkra ramma sem þarf að fylla inn í. Kafli stillir í hvaða röð textinn þinn
            kemur á myndefnið, kafli 1 kemur þá fyrstur, kafli 2 á eftir honum og koll af kolli. Byrjunartíminn er tíminn sem að textinn
            birtist á og hverfur á endatímanum. Athugaðu að tíminn er stilltur eftir (00.00.00, 000) klukkutíma.mínutum.sekundum, rammar.
            Að lokum kemur síðan inn textastrengurinn sem á að birtast á ákveðnu tímabili. 
            Til að bæta við nýrri línu er þrýst á "Bæta við línu" og kemur þá inn annað svona sett af römmum neðst.    
        </p>
    </div>
    <h3>Hvernig bý ég til nýjan aðgang?</h3>
    <div>
        <p>
            Efst uppi í hægra horninu má sjá hlekk sem á stendur @Html.ActionLink("\"Nýskrá\"", "Register", "Account").
            Ef smellt er á þann hlekk opnast nýskráningarsíða þar sem fylla þarf út upplýsingar um notanda.
            Þegar smellt er á nýskrá hnappinn verður nýr notandi til og getur viðkomandi eftir það innskráð sig með sínu notendanafni og lykilorði.
        </p>
    </div>
    <h3>Hvernig óska ég eftir texta</h3>
    <div>
        <p>
            Til þess að óska eftir skjátexta fyrir myndefni þarf notandi að vera innskráður.
            Því næst velur notandinn flipann sem á stendur @Html.ActionLink( "\"Beiðnir\"", "Requests", "ListRequest" ). Þar er smellt á @Html.ActionLink("\"græna plús hnappinn\"", "NewRequest", "ListRequest"), þá er notanda beint inn á nýja síðu þar
            sem fylla verður út helstu upplýsingar um myndefni.
            Þegar allar nauðsynlegar upplýsingar hafa verið settar inn er hægt að senda inn beiðnina.
        </p>
    </div>
    <h3>Hvernig leita ég af texta?</h3>
    <div>
        <p>
            Hægt er að leita að textum eftir flokkum  undir @Html.ActionLink("\"Flokkar\"", "Categories", "Category")  flipanum.
            Textum er raðað í stafrófsröð eftir heiti mynda í @Html.ActionLink("\"Textar A-Ö\"", "AlphabetizedTexts", "ListTranslations") flipanum.
            Einnig er hægt að leita að texta fyrir ákveðina mynd  í leitarkassa bæði á @Html.ActionLink("\"forsíðu\"", "Home") og í flipanum
            @Html.ActionLink( "\"Textar A-Ö\"", "AlphabetizedTexts", "ListTranslations" ).
        </p>
    </div>
    <h3>Af hverju þarf ég að vera innskráður?</h3>
    <div>
        <p>
            Innskráðir notendur hafa aðgang að fleiri aðgerðum en þeir notendur sem ekki eru innskráðir.
            Sem dæmi geta innskráðir notendur breytt þýðingum ásamt því að geta bætt við nýjum einnig geta þeir sent inn beiðnir, þýðingar,
            kosið upp fyrri beiðnir og geta uppfært lýsingu á myndefni.
        </p>
    </div>
    <h3>Hvernig nota ég textann sem ég sótti?</h3>
    <div>
        <p>Þú sækir .srt skránna með þýðingunni og byrjar að spila myndefnið í vlc og dregur .srt skránna yfir í spilarann.</p>
    </div>
    <h3>Hvað geri ég ef ég gleymi notendanafn/lykilorðinu mínu?</h3>
    <div>
        <p>
            Ef lykilorð hefur gleymst er hægt að ýta á @Html.ActionLink( "\"Gleymt Lykilorð\"", "LostPassword", "Account" ) á
            innskráningarsíðunni og setja þar inn tölvupóstinn sinn og við sendum þér notendanafn og nýtt lykilorð í tölvupósti.
            Athugaðu að það getur tekið nokkrar mínútur fyrir lykilorðið að berast.
        </p>
    </div>
    <h3>Hvernig get ég lagað þýðingu sem er nú þegar til?</h3>
    <div>
        <p>
            Til þess að laga þýðingu verður þú að vera innskráður. Þegar ákveðin mynd er valin þá er hægt að laga þýðingu með “Breyta þýðingu”
            hnappinum neðst á síðunni.
        </p>
    </div>
    <h3>Munið þið nokkurn tíma deila upplýsingunum sem ég gef ykkur?</h3>
    <div>
        <p>Nei, við munum aðeins nota upplýsingarnar til þess að geta sent þér gleymt lykilorð.</p>
    </div>
    <h3>Þýðingin sem ég sótti er illa þýdd og/eða óviðeigandi, get ég tilkynnt þýðanda til stjórnanda?</h3>
    <div>
        <p>
            Við viljum endilega vita af því ef þýðing er ekki til fyrirmyndar.
            Niðri í hægra horninu er @Html.ActionLink( "\"Hafðu samband\"", "Contact", "Home" ) hnappur.
            Endilega sendu okkur notendanafn þýðanda og nafnið á tiltekinni þýðingu sem rætt er um.
        </p>
    </div>
</div>

<script src="~/Scripts/jquery-ui-1.10.4.custom.js"></script>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<link rel="stylesheet" type="text/html" href="~/Content/jquery-ui-1.10.4.custom.css" />
@section Scripts {
    @Scripts.Render( "~/bundles/jqueryval" )
}

3viknavinir/Views/Home/Index.cshtml
    @model _3viknavinir.Models.IndexViewModel
    @{
        ViewBag.Title = "SÍÁT";
    }
    @*Liljar*@
    <div id="welcome">
        <p>
            Velkominn á síðu Samfélags Íslensks Áhugafólks um Texta!
            Hér getur þú sótt, deilt, þýtt og spáð í textaþýðingum fyrir myndefni.
        </p>
    </div>
    @*Erla*@
    <div id="searchBox">
        @using (Html.BeginForm("SearchMediaView", "Search", FormMethod.Get))
        {
            @Html.TextBox("SearchString")
            <input type="submit" value="Leita" class="btn btn-default" id="searchButton" />
        }
    </div>
    
    <div class="row">
    <div>
        <table id="homePageTable-2" class="table-striped">
            <thead>
                <tr class="homePageTableRows">
                    <th>Nýjustu Textar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.recentMedia)
                {
                    <tr class="homePageTableRows">
                        <td>@Html.ActionLink(item.title, "Details", "Translation", new { id = item.ID }, null) (@item.yearOfRelease)</td>
                    </tr>
                }
            </tbody>
        </table>
    <table id="homePageTable-1" class="table-striped">
        <thead>
            <tr class="homePageTableRows">
                <th>Nýjustu Beiðnir</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.recentRequests)
            {
                <tr class="homePageTableRows">
                    <td>@item.title (@item.yearOfRelease)</td>
                </tr>
            }
        </tbody>
    </table>
</div>
     </div>
   

3viknavinir/Views/Home/ProcessRequest.cshtml
@{
    var userName = Request["userName"];
    var userEmail = Request["userEmail"];
    var userRequest = Request["userRequest"];
    var errorMessage = "";
    try
    {
        WebMail.SmtpServer = "smtp.gmail.com";
        WebMail.EnableSsl = true;
        WebMail.SmtpPort = 587;
        WebMail.UserName = "siatnoreply@gmail.com";
        WebMail.Password = "stringerla";
        WebMail.From = "siatnoreply@gmail.com";
        // Send email
        WebMail.Send(to: "siatnoreply@gmail.com",
            subject: "Fyrirspurn frá - " + userName,
            body: userName + " með tölvupóstinn " + userEmail + " hafði samband, hann/hún vildi láta okkur vita af þessu: " + userRequest
        );
        WebMail.Send(to: userEmail, 
            subject: userName + ", þú sendir fyrirspurn á SÍÁT",
            body: "Takk fyrir að hafa samband við okkur, við munum svara beiðni þinni eins fljótt og hægt er. Hún hljómaði svona: " + userRequest
        );
    }
    catch (Exception ex)
    {
        errorMessage = ex.Message;
    }
}

@{
    ViewBag.Title = "Þú hafðir samband";
}

    <div class="breadcrumb">
        <ul class="crumbs">
            <li class="crumb crumb-first">
                @Html.ActionLink("SÍÁR", "Index", "Home")
            </li>
            <li class="crumb crumb-last">
                <span class="crumb-seperator"> > </span>
                @Html.ActionLink("Hafa samband", "Contact", "Home")
            </li>
            <li class="crumb crumb-last">
                <span class="crumb-seperator"> > </span>
                @Html.ActionLink("Fyrirspurn send", "ProcessRequest", "Contact")
            </li>
        </ul>
    </div>
    
    @if (errorMessage == "")
    {
        <h2>@ViewBag.Title</h2>

    <p>Takk fyrir að hafa samband við okkur, <b>@userName</b>.</p>
        <p>
            Við höfum fengið fyrirspurnina þína og munum bregðast við eins fljótt og hægt er.
            Við sendum þér einnig tölvupóst með fyrirspurninni þinni, vertu sem oftast í sambandi!
            Þetta eru skilaboðin sem þú sendir:
        </p>
        <p><b>@userRequest</b></p>
    }
    else
    {
        <h2>Skilaboð mistókust</h2>
    <p>Takk fyrir að reyna hafa samband við okkur, <b>@userName</b>.</p>
        
        <p><b>Því miður var fyrirspurnin þín <em>ekki</em> send.</b></p>
        <p>
            Líklegast var tölvupóstfangið sem þú settir inn ekki á réttu formi. Endilega reyndu aftur.
        </p>
      
    }